class Chapter04:
    exercises = [
        "4.1 - Pizzas",
        "4.2 - Animals",
        "4.3 - Counting to Twenty",
        "4.4 - One Million",
        "4.5 - Summing a Million",
        "4.6 - Odd Numbers",
        "4.7 - Three",
        "4.8 - Cubes",
        "4.9 - Comprehension of cubes",
        "4.10 - Slices",
        "4.11 - My pizzas, your pizzas",
        "4.12 - More Ties",
        "4.13 - Buffet",
        "4.14 - PEP 8",
        "4.15 - Code Review",
    ]
    topics = [
        "4 ■ Trabalhando com listas",
        "Percorrendo uma lista inteira com um laço",
        "Observando os laços com mais detalhes",
        "Executando mais tarefas em um laço for",
        "Fazendo algo após um laço for",
        "Evitando erros de indentação",
        "Esquecendo-se de indentar",
        "Esquecendo-se de indentar linhas adicionais",
        "Indentando desnecessariamente",
        "Indentando desnecessariamente após o laço",
        "Esquecendo os dois-pontos",
        "Criando listas numéricas",
        "Usando a função range()",
        "Usando range() para criar uma lista de números",
        "Estatísticas simples com uma lista de números",
        "List comprehensions",
        "Trabalhando com parte de uma lista",
        "Fatiando uma lista",
        "Percorrendo uma fatia com um laço",
        "Copiando uma lista",
        "Tuplas",
        "Definindo uma tupla",
        "Percorrendo todos os valores de uma tupla com um laço",
        "Sobrescrevendo uma tupla",
        "Estilizando seu código",
        "Guia de estilo",
        "Indentação",
        "Tamanho da linha",
        "Linhas em branco",
        "Outras diretrizes de estilo",
        "Resumo",
    ]
