class chapter02:
    exercises = [
        "2.3 - Mensagem pessoal",
        "2.4 - Letras maiúsculas e minúsculas em nomes",
        "2.5 - Citação famosa",
        "2.6 - Citação famosa 2",
        "2.7 - Removendo caracteres em branco de nomes",
        "2.8 - Número oito",
        "2.9 - Número favorito",
        "2.10 - Acrescentando comentários",
        "2.11 - Zen de Python",
    ]

    topics = [
        "2 ■ Variáveis e tipos de dados simples",
        "O que realmente acontece quando executamos hello_world.py",
        "Variáveis",
        "Nomeando e usando variáveis",
        "Evitando erros em nomes ao usar variáveis",
        "Strings",
        "Mudando para letras maiúsculas e minúsculas em uma string usando",
        "métodos",
        "Combinando ou concatenando strings",
        "Acrescentando espaços em branco em strings com tabulações ou quebras",
        "de linha",
        "Removendo espaços em branco",
        "Evitando erros de sintaxe com strings",
        "Exibindo informações em Python 2",
        "Números",
        "Inteiros",
        "Números de ponto flutuante",
        "Evitando erros de tipo com a função str()",
        "Inteiros em Python 2",
        "Comentários",
        "Como escrever comentários?",
        "Que tipos de comentário você deve escrever?",
        "Zen de Python",
        "Resumo",
    ]
