class Chapter04:
    exercises = [
        "5.1 - Conditional Tests",
        "5.2 - More Conditional Tests",
        "5.3 - Alien Colors #1",
        "5.5 - Alien Colors #3",
        "5.6 - Stages of Life",
        "5.7 - Favorite Fruit",
        "5.8 - Hello Admin",
        "5.9 - No Users",
        "5.10 - Checking Usernames",
        "5.11 - Ordinal Numbers",
    ]
    topics = [
        "5 ■ Instruções if",
        "Um exemplo simples",
        "Testes condicionais",
        "Verificando a igualdade",
        "Ignorando as diferenças entre letras maiúsculas e minúsculas ao verificar",  # noqa
        "a igualdade",
        "Verificando a diferença",
        "Comparações numéricas",
        "Testando várias condições",
        "Verificando se um valor está em uma lista",
        "Verificando se um valor não está em uma lista",
        "Expressões booleanas",
        "Instruções if",
        "Instruções if simples",
        "Instruções if-else",
        "Sintaxe if-elif-else",
        "Usando vários blocos elif",
        "Omitindo o bloco else",
        "Testando várias condições",
        "Usando instruções if com listas",
        "Verificando itens especiais",
        "Verificando se uma lista não está vazia",
        "Usando várias listas",
        "Estilizando suas instruções if",
        "Resumo",
    ]
