class Chapter01:
    topics = (
        "Capítulo 1 • Informações preliminares",
        "1.1 De que se trata estelivro?",
        "Quais tipos dedados?",
        "1. 2 Por que Python para análise dedados?",
        "Python como aglutinador",
        "Resolvendo o problema de 'duas linguagens'",
        "Por que não Python?",
        "1. 3 Bibliotecas Python essenciais",
        "NumPy",
        "pandas",
        "matplotlib",
        "IPython e Jupyter",
        "SciPy",
        "scikitlearn",
        "statsmodels",
        "1.4 Instalação e configurao",
        "Windows",
        "Apple (OS X.MacOS)",
        "GNULinux",
        "Instalando ou atualizando pacotesPython",
        "Python 2 e Python",
        "Ambientes de desenvolvimento integrado (IDEs) e editoresde",
        "texto",
        "1. 5 Comunidade e conferncias",
        "1. 6 Navegando pelolivro",
        "Exemplos decdigo",
        "Dados para os exemplos",
        "Convenções de importao",
        "Jargão",
    )
    pass
